on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.

concurrency:
  group: angular-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  build:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - name: Set vars to env
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV

      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Set up JDK 21 for openapi-generator-cli
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v5
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: env replacement
        run: node update-environment.js

      - name: Install dependencies
        run: npm ci

      - name: Generate OpenAPI client
        run: |
          if [ "${{ inputs.environment }}" = "prod" ]; then
            npm run generate:api:prod
          else
            npm run generate:api
          fi

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:headless

      - name: Build
        run: npm run build -- --configuration production

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v6
        with:
          name: deploy_dist
          path: dist

  containerization:
    environment: ${{ inputs.environment }}
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download build
        uses: actions/download-artifact@v7
        with:
          name: deploy_dist
          path: dist

      # - name: test
      #   run: pwd && ls -lR

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/angular/Dockerfile
          push: true
          provenance: false
          tags: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ vars.ANGULAR_GAR_REPO }}/${{ secrets.ANGULAR_IMAGE_NAME }}:${{ inputs.environment }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy'
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ secrets.ANGULAR_IMAGE_NAME }}-${{ inputs.environment }}
          image: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ vars.ANGULAR_GAR_REPO }}/${{ secrets.ANGULAR_IMAGE_NAME }}:${{ inputs.environment }}-${{ github.sha }}
          region: ${{ secrets.GOOGLE_REGION }}
          suffix: ${{ github.sha }}
          env_vars: |
            NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
            NGINX_HOST=${{ vars.HOST_URL }}
