on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: Name of the target environment.

concurrency:
  group: socket-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: socket-server/package-lock.json

      - name: Install dependencies
        run: |
          cd socket-server
          npm ci

  containerization:
    environment: ${{ inputs.environment }}
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build and push image to registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/socket/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ vars.SOCKET_GAR_REPO }}/${{ secrets.SOCKET_IMAGE_NAME }}:${{ inputs.environment }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy'
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: ${{ secrets.SOCKET_IMAGE_NAME }}-${{ inputs.environment }}
          image: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/${{ vars.SOCKET_GAR_REPO }}/${{ secrets.SOCKET_IMAGE_NAME }}:${{ inputs.environment }}-${{ github.sha }}
          region: ${{ secrets.GOOGLE_REGION }}
          suffix: ${{ github.sha }}
          env_vars: |
            NODE_ENV=${{ inputs.environment == 'dev' && 'development' || 'production' }}
            CORS_DOMAIN=${{ vars.HOST_URL }}
